name: Build node js application image
on:
  push:
    branches: [ main ] 

jobs:
  build-and-push:
    name: Build and Push to AWS ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push the Image to AWS ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-ecr-repo
        IMAGE_TAG: latest
      run: |
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Register Task Definition
        id: register-task-def
        run: |
          aws ecs register-task-definition --family my-task-family --container-definitions '[{"name":"my-container","image":"'"${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"'"}]'

    - name: Update ECS Service
        id: update-ecs-service
        run: |
          aws ecs update-service --cluster my-cluster --service my-service --task-definition my-task-family:1
